# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
# Azure Key Vault
# Download Azure Key Vault secrets
- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'hazzat-api-ppe - Azure'
    keyVaultName: 'hazzat-api-ppe'
    secretsFilter: 'hazzatdnn-ConnectionString'

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
   cd src
    npm install
    npm run build
    npm run test
  displayName: 'npm install and build'
  env:
    CUSTOMCONNSTR_DBCONNECTIONSTRING: $(hazzatdnn-ConnectionString)

- task: CopyFiles@2
  displayName: 'Copy Deployment files to: $(TargetFolder)'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
        src/dist/*/**
        src/node_modules/**/*
        src/Web.config
        src/Web.Debug.config
    TargetFolder: '$(Build.ArtifactStagingDirectory)\ArtifactsToBeArchived'

- task: ArchiveFiles@1
  displayName: 'Archive files'
  inputs:
    rootFolder: '$(Build.ArtifactStagingDirectory)\ArtifactsToBeArchived'
    includeRootFolder: false

- task: CopyFiles@2
  displayName: 'Copy File to: $(TargetFolder)'
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)\ArtifactsToBeArchived'
    Contents: '$(Build.BuildId).zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\ArtifactsToBePublished'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\ArtifactsToBePublished'
